### ISSUE TITLE
need add limit 0.10

### ISSUE THREAD

**Issue by maoxianfly** [mattsta/krmt#6]
I think georadius/georadiusbymember need to add a limit parameter, return a partial result. What do you think?

**Comment by mattsta** [comment]
Thanks for the suggestion!  It is a good idea, but the way radius search process works, there's not a _clean_ way to get it done.

The server would have to retrieve the _entire_ radius, sort the entries by distance from the center, then filter elements from the sorted result.

So, it is possible to limit the number of return values, but it wouldn't make the query any faster since it has to still get the entire radius to filter the results.  Every new call would re-do all the work from the previous call just to filter our a few more elements.  (That's the problem with searching a 2-D grid instead of just a sorted set of integers.)

The current geo searching probably isn't great if your radius contains thousands of elements, but you can always shrink your radius and shift your center point around to get fewer entries per call.  :)

I'll keep your request in mind if any refactor/improvements happen around here.
