### ISSUE TITLE
Are redis module commands available through lua scripts?

### ISSUE THREAD

**Issue by joeandrews** [mattsta/krmt#8]
Great work on dynamic redis.

I am looking to implement geo-redis, but want to access the functionality via a lua script.  Is this possible? 

Thanks

Joe

**Comment by mattsta** [comment]
Thanks for trying it out!

Many people do use it through a Lua interface (common scenario: PHP redis client doesn't allow arbitrary commands, so if you're using that client, Lua scripts are the only way to go).

The only downside of the Lua interface is: if you are only wrapping *one* command, it can be 10% to 50% slower than the raw command directly (because of the way Redis makes Lua call Redis commands).  But, even with that overhead loss, it's usually not a problem unless you're pushing 50k+ lookups per second (based on your own system speeds, memory interface, etc).

So, you'd just do a regular `redis.call('georadius', ...)` and get the results back as a Lua table (or you can just `return` it directly from Lua to generate a regular Redis reply).

**Comment by joeandrews** [comment]
Awesome, thanks will let you know how I get on.
